// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using HotelsGarden.Models.Domain.Expedia;

namespace HotelsGarden.Models.Domain.Expedia
{

    public class Hotel
    {

        [JsonProperty("offerDateRange")]
        public OfferDateRange OfferDateRange { get; set; }

        [JsonProperty("destination")]
        public Destination Destination { get; set; }

        [JsonProperty("hotelInfo")]
        public HotelInfo HotelInfo { get; set; }

        [JsonProperty("hotelUrgencyInfo")]
        public HotelUrgencyInfo HotelUrgencyInfo { get; set; }

        [JsonProperty("hotelPricingInfo")]
        public HotelPricingInfo HotelPricingInfo { get; set; }

        [JsonProperty("hotelUrls")]
        public HotelUrls HotelUrls { get; set; }
    }

}
