// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace HotelsGarden.Models.Domain.Expedia
{
    public class HotelInfo
    {
        [JsonProperty("hotelId")]
        public string HotelId { get; set; }

        [JsonProperty("hotelName")]
        public string HotelName { get; set; }

        [JsonProperty("localizedHotelName")]
        public string LocalizedHotelName { get; set; }

        [JsonProperty("hotelDestination")]
        public string HotelDestination { get; set; }

        [JsonProperty("hotelDestinationRegionID")]
        public string HotelDestinationRegionID { get; set; }

        [JsonProperty("hotelLongDestination")]
        public string HotelLongDestination { get; set; }

        [JsonProperty("hotelStreetAddress")]
        public string HotelStreetAddress { get; set; }

        [JsonProperty("hotelCity")]
        public string HotelCity { get; set; }

        [JsonProperty("hotelProvince")]
        public string HotelProvince { get; set; }

        [JsonProperty("hotelCountryCode")]
        public string HotelCountryCode { get; set; }

        [JsonProperty("hotelLatitude")]
        public double HotelLatitude { get; set; }

        [JsonProperty("hotelLongitude")]
        public double HotelLongitude { get; set; }

        [JsonProperty("hotelStarRating")]
        public string HotelStarRating { get; set; }

        [JsonProperty("hotelGuestReviewRating")]
        public double HotelGuestReviewRating { get; set; }

        [JsonProperty("hotelReviewTotal")]
        public int HotelReviewTotal { get; set; }

        [JsonProperty("hotelImageUrl")]
        public string HotelImageUrl { get; set; }

        [JsonProperty("vipAccess")]
        public bool VipAccess { get; set; }

        [JsonProperty("isOfficialRating")]
        public bool IsOfficialRating { get; set; }
    }
}
