// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using HotelsGarden.Models.Domain.Expedia;

namespace HotelsGarden.Models.Domain.Expedia
{

    public class HotelUrls
    {

        [JsonProperty("hotelInfositeUrl")]
        public string HotelInfositeUrl { get; set; }

        [JsonProperty("hotelSearchResultUrl")]
        public string HotelSearchResultUrl { get; set; }
    }

}
