// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace HotelsGarden.Models.Domain.Expedia
{
    public class HotelUrls
    {
        [JsonProperty("hotelInfositeUrl")]
        public string HotelInfositeUrl { get; set; }

        [JsonProperty("hotelSearchResultUrl")]
        public string HotelSearchResultUrl { get; set; }
    }
}
