// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using HotelsGarden.Models.Domain.Expedia;

namespace HotelsGarden.Models.Domain.Expedia
{

    public class OfferDateRange
    {

        [JsonProperty("travelStartDate")]
        public int[] TravelStartDate { get; set; }

        [JsonProperty("travelEndDate")]
        public int[] TravelEndDate { get; set; }

        [JsonProperty("lengthOfStay")]
        public int LengthOfStay { get; set; }
    }

}
