// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using HotelsGarden.Models.Domain.Expedia;

namespace HotelsGarden.Models.Domain.Expedia
{

    public class UserInfo
    {

        [JsonProperty("persona")]
        public Persona Persona { get; set; }

        [JsonProperty("userId")]
        public string UserId { get; set; }
    }

}
