// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using HotelsGarden.Models.Domain.Expedia;

namespace HotelsGarden.Models.Domain
{

    public class ExpediaOffers
    {

        [JsonProperty("offerInfo")]
        public OfferInfo OfferInfo { get; set; }

        [JsonProperty("userInfo")]
        public UserInfo UserInfo { get; set; }

        [JsonProperty("offers")]
        public Offers Offers { get; set; }
    }

}
